base_url = "https://halide.cx"

compile_sass = true
build_search_index = false

generate_feeds = true
feed_filenames = ["atom.xml"]
title = "Halide Compression"
author = "Halide Team"
description = "Hi, we're Halide Compression."

[markdown]
[markdown.highlighting]
error_on_missing_language = true
style = "inline"
theme = "catppuccin-frappe"

[extra]
metrics_measured = "Feb 2026"
cmp_encoded = "Feb 2026"
